### ISSUE TITLE
Cannot read property error after upgrade

### ISSUE THREAD

**Issue by JorgenSeemann** [reyntjensw/Homey-FusionSolar#10]
Diag log - ca100552-a4b6-411e-afb1-d1823a1f1aab
Tried reboot app and homey, but this didn't help:/

**Comment by reyntjensw** [comment]
@JorgenSeemann I am seeing this in the logs :

```
Huawei has been initialized
{"data":null,"success":false,"failCode":20001,"params":{"currentTime":1652765355424},"message":null}

```
Meaning there is something wrong with your login on the new api endpoint.

Please install https://homey.app/a/com.huawei.solar/test/ which is using the old api.

I have updated the case to Huawei and as soon as I have info, I'll let you know

**Comment by reyntjensw** [comment]
hi @JorgenSeemann 

Can you login into the web interface of Fusion solar and tell me what the url is when logging in?

When I login I use https://eu5.fusionsolar.huawei.com/, after login my url changes to https://region01eu5.fusionsolar.huawei.com/.

Can you tell me what your region0x server is?

**Comment by reyntjensw** [comment]
@JorgenSeemann please install this new version https://homey.app/a/com.huawei.solar/test/

And also follow this guide https://community.homey.app/t/huawei-solar/61745/2, this should solve the issue

**Comment by reyntjensw** [comment]
@JorgenSeemann can you confirm that the issue is solved please?

**Comment by JorgenSeemann** [comment]
Yes, it seems to be working as expected 😀

fre. 20. maj 2022 20.30 skrev Wouter Reyntjens ***@***.***>:

**Comment by reyntjensw** [comment]
Great thanks!

**Comment by JorgenSeemann** [comment]
Hi Wouter

Having logged in, my URL shows server region02eu5

Br
Jørgen

tor. 19. maj 2022 09.13 skrev Wouter Reyntjens ***@***.***>:

**Comment by reyntjensw** [comment]
Hi Jorgen

You can change it by going to the settings in the app, there you have the option to change the server.

Wouter
________________________________
Van: JorgenSeemann ***@***.***>
Verzonden: dinsdag 11 oktober 2022 10:24
Aan: reyntjensw/Homey-FusionSolar ***@***.***>
CC: Wouter Reyntjens ***@***.***>; State change ***@***.***>
Onderwerp: Re: [reyntjensw/Homey-FusionSolar] Cannot read property error after upgrade (Issue #10)


Hi Wouter

Having logged in, my URL shows server region02eu5

Br
Jørgen

tor. 19. maj 2022 09.13 skrev Wouter Reyntjens ***@***.***>:

**Comment by reyntjensw** [comment]
![image](https://user-images.githubusercontent.com/4648544/195077934-be384775-92e7-40ea-9e6d-a42ccf064051.png)
