### ISSUE TITLE
Change of server address of Huawei Solar Server

### ISSUE THREAD

**Issue by Basdekoningh** [reyntjensw/Homey-FusionSolar#106]
Good morning Wouter,

Is it possible for you to change the webserver addres in the Homey App for Huawei Solar?
It seems that the addres has changed (see other post on Github)

**Comment by reyntjensw** [comment]
Hi @Basdekoningh please continue in 1 issue please https://github.com/reyntjensw/Homey-FusionSolar/issues/103
