### ISSUE TITLE
Connection lost, than Error retrieving data OR not possible to login OR 'null device' (starting around 17/1/2024) 

### ISSUE THREAD

**Issue by Luc0001** [reyntjensw/Homey-FusionSolar#109]
Hi Wouter,

I see I'm not the only one who has lost his PV installation (Huawei) in Homey Pro.
I was waiting for a solution, as you usually come-up with within a few days, but now, after +/_ one month (and multiple Homey Pro restart/Huawei Homey app restart & reinstall) I contact you to see if there is a solution?

Looking forward to your reply my kind regards... Luc

**Comment by reyntjensw** [comment]
Hi Luc

Please take a look at this issue, there I'm explaining what the issue is https://github.com/reyntjensw/Homey-FusionSolar/issues/104#issuecomment-1937201064. 

It has no use to open new issues for the same problem.

**Comment by Luc0001** [comment]
Hi Wouter,

So if I understand your ref. there is no solution currently.
I can't help at dev.level, not my cup of tee, sorry.

I'll check once and a while.

Best regards, good luck and thx a lot for your work.

Luc


Mvg...Luc
________________________________
