### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by acaenepeel** [reyntjensw/Homey-FusionSolar#15]
Hi,

When adding a new device I can login but then I get this error: Cannot read property 'name' of undefined.

How can I fix this?

My diagnostics report is: 60d621ce-78ae-4925-893c-b9dad9bc27df.

Kind regards

**Comment by reyntjensw** [comment]
@acaenepeel can you please install the latest version and try again?

**Comment by reyntjensw** [comment]
@acaenepeel  can I close this issue?
Was your problem solved?

**Comment by acaenepeel** [comment]
@reyntjensw , you can close this issue, thanks.
