### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by omgoransson** [reyntjensw/Homey-FusionSolar#17]
Hi,

I can’t login with your app. It works fine with FusionSolar and I even confirmed with Huawei that I have an open and active account.
What am I missing?
Kindly,
Ola

**Comment by omgoransson** [comment]
I sent a diagnostic report with ID:
0acd7b30-e088-4cc7-b50b-409b2a189751

**Comment by reyntjensw** [comment]
Hi @omgoransson 

You need to request an API account.
Did you request one?

Wouter

**Comment by omgoransson** [comment]
I did not. Rectifying that now. Mvh,
Ola Göransson
***@***.*** nov. 2022 kl. 07:18 skrev Wouter Reyntjens ***@***.***>:﻿
Hi @omgoransson
You need to request an API account.
Did you request one?
Wouter

**Comment by reyntjensw** [comment]
@omgoransson was your issue solved?

**Comment by omgoransson** [comment]
Thank you for following up. The issue is with Huawei. They refuse to open an api account because of a data input error on their part. I will close the issue now.
