### ISSUE TITLE
Power per hour

### ISSUE THREAD

**Issue by ludwich** [reyntjensw/Homey-FusionSolar#19]
Could you add the possibility to track hourly generation? meter_power.hour. Would really love that. And thanks for a good app.

**Comment by reyntjensw** [comment]
@ludwich from what I can see, the hourly data is not available by default.

`{
  total_income: 1028.268,
  total_power: 9980.12,
  day_power: 4.15,
  day_income: 1.014,
  real_health_state: 3,
  month_power: 88.71
}`

**Comment by ludwich** [comment]
My bad thought we got the same data as we do from the OpenAPI.
