### ISSUE TITLE
Power by the hour integration

### ISSUE THREAD

**Issue by ludwich** [reyntjensw/Homey-FusionSolar#20]
Adding Power by the hour so i can track the real money gained by cells is not working. It is possible to add but it does not read any values.

In homey energy it is also displaying 0.

This could be solved by adding measure_power capability. This way with Power By The Hour we could actually see for real how much we saved since that app can take in an energy tarrif which is hourly updated in a flow based on hourly cost.

**Comment by ludwich** [comment]
@reyntjensw i am a javascript/ts dev as well and could support on modbus feature if you want to. Tried to extend main with more capabilities but get a weird error on includes TypeError: Cannot read properties of undefined (reading '0'). Commented out the code if statements where includes is used by still getting it.

**Comment by ludwich** [comment]
Yes when i add measure_power i get the error. Will try something else since it might be a problem with setting a value like that when we have capabilities below it. Will branch and make PR.

**Comment by ludwich** [comment]
@reyntjensw yes i am getting this issue from main straight away without any changes.

**Comment by reyntjensw** [comment]
> @reyntjensw yes i am getting this issue from main straight away without any changes. my bad since i had the app installed as well i was getting throttled. Removed now and will start again later today,

The error handling regarding the throttling needs to be improved.

**Comment by ludwich** [comment]
Resolved
