### ISSUE TITLE
Battery data not working

### ISSUE THREAD

**Issue by Vaggan71** [reyntjensw/Homey-FusionSolar#29]
Hello,
I have battery for my system that stopped giving info since version 1.0.34.
Even version 1.0.35 does not work; in the code it looks like you just changed that the battery id must not be null or empty.

It is stuck at 65% and Charge battery -0.38.

Is there any way I can install version 1.0.33 again; it worked perfectly for me.

**Comment by reyntjensw** [comment]
@ludwich can you take a look at this please?

**Comment by ludwich** [comment]
@Vaggan71 I don´t have a battery myself and the logic for setting these values are the same as 1.0.33 but if you send my your login credentials i could look at your setup. ludwig.hallgren@gmail.com

**Comment by reyntjensw** [comment]
@Vaggan71 the new build is live, can you please check version 1.0.36?

**Comment by Vaggan71** [comment]
Thx, its working.
