### ISSUE TITLE
Cannot read property ‘name’ of undefined

### ISSUE THREAD

**Issue by ygel** [reyntjensw/Homey-FusionSolar#41]
Hi,

as many others I have issues adding my inverter. I have got an API account but still get same error message. Could you help me please?

regards

 494a96e8-e33b-4c87-865d-9d621375e706

**Comment by reyntjensw** [comment]
Hi @ygel I see that no systems are connected to this  account.
Can you please get into contact with your installer?

`systems :
undefined`

**Comment by reyntjensw** [comment]
I have released a new version, can you please try again?
