### ISSUE TITLE
 Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by dsellig** [reyntjensw/Homey-FusionSolar#56]
Sorry to create another thread with the same error. I'm on 1.0.52. I've tried logging in using the API credentials I was giving by my installer as well as using the 'regular' credentials I use to login on Fusionsolar. Both give the same error.

892c2645-ce97-49ec-82cb-a0783750b297

**Comment by Solsind** [comment]
7b33ff2a-6da3-48fe-929b-8e65f62d936f this code came after reporting. It does not work. 
![IMG_3978](https://user-images.githubusercontent.com/107113710/236048832-c111bcc1-9830-43e4-af4b-00d8a25b715b.png)
![IMG_3977](https://user-images.githubusercontent.com/107113710/236048839-c887d4ed-fb04-49f1-b074-ab973b7b260e.png)

**Comment by Solsind** [comment]
I installed it, but same issue with both. Strange when this api could speak with my huawei installation 6 Months agoDen 9. maj 2023 kl. 20.23 skrev Wouter Reyntjens ***@***.***>:﻿
@Solsind can you please install the test version?
https://homey.app/nl-be/app/com.huawei.solar/Huawei-Solar/test/

**Comment by dsellig** [comment]
> 

The 401 error was due to me trying the 'Systems after 2023' device instead. Both give the same error.

Following the Huawei API documentation login:
![afbeelding](https://github.com/reyntjensw/Homey-FusionSolar/assets/93187617/1714ea5d-0820-4f7b-9a7f-a1f7cec6d42c)

getStationList:
![afbeelding](https://github.com/reyntjensw/Homey-FusionSolar/assets/93187617/01a95c03-63ad-4b9f-b0be-3232f0282e97)

getDevList - including Powersensor:
![afbeelding](https://github.com/reyntjensw/Homey-FusionSolar/assets/93187617/d83e034d-7d18-4d59-9d7a-0b1af1ba2f4d)

I think this looks good, no?

**Comment by reyntjensw** [comment]
@dsellig please try the new test version

**Comment by dsellig** [comment]
> @dsellig please try the new test version

Same error on .53: 90586390-8684-4a8c-9efa-4e98209ad2fe

Any idea?

**Comment by reyntjensw** [comment]
@dsellig can you share with me your login?
If possible via a dm through the Homey community

**Comment by reyntjensw** [comment]
@dsellig can you try again?

**Comment by dsellig** [comment]
> @dsellig can you try again?

Thanks! On .56 now, it worked for about 2 minutes at 6:30 this morning. Some values showed up and then it stopped working: it showed the same error on the values card.

it then started working again. I went to advanced settings (where there is also an option for regio settings - I didn’t modify this!), and set ‘home battery’ to yes. It stopped working after that.

I tried restarting the app and reinstalling (I mean the integration inside Homey, not the Homey app).

133912d0-c5f6-48c0-8519-94688fbaa62b

**Comment by reyntjensw** [comment]
@dsellig can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by dsellig** [comment]
Thanks for this! Unfortunately same error: 1b33d5f7-e79d-4f47-bcb9-5775eb42dbff
—> please note this was the first error, afterwards I tried the other login methods again.

When using the API credentials, using pre 2023, I now actually get another error: Invalid Capability: inverter_temperature

1db2f316-ad0f-4d12-bc46-5274d9aadf73

**Comment by reyntjensw** [comment]
@dsellig can you please try the new test version (https://homey.app/a/com.huawei.solar/test/).
Also please try the web version instead of the api version

**Comment by dsellig** [comment]
Same error on 2.0.4 with web auth: 36e2c8f7-a5d2-49cf-aeb3-8b72a14327de

I selected region 02, which I use to login on the website.

**Comment by reyntjensw** [comment]
@dsellig could you please share with me your credentials via DM in the Homey community?

**Comment by dsellig** [comment]
Done

**Comment by reyntjensw** [comment]
Perfect, I found the issue, can you please install 2.0.5 and try again?

**Comment by dsellig** [comment]
Works great now! Thanks for this.

The battery values are not being loaded but I guess that might be one of the fields that are not yet implemented.

Thanks!

**Comment by reyntjensw** [comment]
Thanks, for now just restart the app to see the battery values

Op 21 mei 2023 22:48 schreef dsellig ***@***.***>:

Works great now! Thanks for this.

The battery values are not being loaded but I guess that might be one of the fields that are not yet implemented.

Thanks!
