### ISSUE TITLE
Device Unavailable in version 1.0.56 (HP2023)

### ISSUE THREAD

**Issue by Vaggan71** [reyntjensw/Homey-FusionSolar#58]
Stopped working after version 1.0.56.
Device Unavailable, and in my flows all says unavailable.

I have HP2023.
/Magnus

**Comment by Vaggan71** [comment]
Its working if I add a new "before 2023".
But all my flows is broken.

**Comment by ludwich** [comment]
What do we have to re- add the system?

**Comment by mackewigren** [comment]
Also device unavailable. Installed 2022.

**Comment by reyntjensw** [comment]
> @reyntjensw same issue for me.
> 
> Can you push the code so i can see the diff.

The code is in this PR https://github.com/reyntjensw/Homey-FusionSolar/pull/55
The issue has to do with the backend server, I commented that one out and replaced it with the intl option.

I don't have my own account so I cannot test thoroughly.

Error 305 seems to be caused by the querying the wrong server

**Comment by reyntjensw** [comment]
> Its working if I add a new "before 2023". But all my "solar" flows is broken.

That is normal when you remove a device, you can replace the broken device.

**Comment by ludwich** [comment]
No we have to add a total new one so all flows and power by the hour data
is lost.


Den tors 11 maj 2023 19:44Wouter Reyntjens ***@***.***> skrev:

**Comment by Vaggan71** [comment]
> > Its working if I add a new "before 2023". But all my "solar" flows is broken.
> 
> That is normal when you remove a device, you can replace the broken device.

I haven't removed any device, it was unavailable after the version 1.0.56 auto installed.

**Comment by Vaggan71** [comment]
Now in version 1.0.57 its stoppad working agan.

**Comment by Vaggan71** [comment]
@reyntjensw version 1.0.58 is working but my daily and total will not update.

**Comment by reyntjensw** [comment]
@Vaggan71 can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by mackewigren** [comment]
I tried the 2.0.3 experimental version. Had earlier experimental version before. 

Doesn’t work for me. Tried both “Before 2023” and “Web login”. 

With “Before 2023” the device is found but I get the red triangle. Then I try to change region/server and then get error about “Invalid capability inverter temperature”. Cannot get passed this so it doesn’t work. The device is added but with wrong settings. 

With “Web login” it states 1 device found but then get error about “Cannot read property ‘name’ of undefined” so the device is not added.

**Comment by Vaggan71** [comment]
@reyntjensw 
I have tried version 2.0.3 but it doesn't work (before 2023). Web login does not work because I am in region02

**Comment by reyntjensw** [comment]
@Vaggan71 can you please try the web login again? https://homey.app/a/com.huawei.solar/test/

**Comment by mackewigren** [comment]
I also tried again. Could choose region first but then same message anyway.

**Comment by Vaggan71** [comment]
@reyntjensw  In version 2.05 web login works, but battery does not work; see attached picture.

![Solar](https://github.com/reyntjensw/Homey-FusionSolar/assets/104837441/2cac9cfa-35a4-4e2f-acad-23419de21bc6)

**Comment by mackewigren** [comment]
Works fine (it seems) after restart also with battery
