### ISSUE TITLE
Server not defined in 1.0.57

### ISSUE THREAD

**Issue by ludwich** [reyntjensw/Homey-FusionSolar#59]
Can please start to test your updates. Last update i hade to remove and readd so broke all data and flows and this Update it is not working only says server not defined.

**Comment by reyntjensw** [comment]
@ludwich since a couple of weeks I have no api credentials so I am not able to test the releases.
I'm working on a way to use the website credentials instead of the openapi, because this is not maintainable for me

**Comment by ludwich** [comment]
If you ping me and leave a test version for 1-2 weeks we can easily test it.

**Comment by Tschurl** [comment]
If possible, I would like to help you?

8d7733e1-bdb4-4ca2-9bc0-89d13e0c3228

**Comment by ludwich** [comment]
@reyntjensw Cant see the latest PR. If you push them I can have a look.

**Comment by reyntjensw** [comment]
@ludwich the test version is available https://homey.app/a/com.huawei.solar/test/

Please let me know what de findings are.
This is the PR I'm working in https://github.com/reyntjensw/Homey-FusionSolar/pull/55

**Comment by JorgenSeemann** [comment]
I confirm the .58 version has removed the "server is not defined " error.
On my system it seems to work as normal again.

Cheers
Jørgen

tir. 16. maj 2023 15.04 skrev Wouter Reyntjens ***@***.***>:

**Comment by ludwich** [comment]
5 minut values are updated correctly. Waiting to see if daily gets updated

**Comment by ludwich** [comment]
My daily and total will not update. Will check again tomorrow.

**Comment by JorgenSeemann** [comment]
Looks like same for me.

tir. 16. maj 2023 18.04 skrev ludwich ***@***.***>:

**Comment by JorgenSeemann** [comment]
Daily & monthly yield and total power
All showing last update is 2 days ago 😀

tir. 16. maj 2023 18.52 skrev Joergen Seemann ***@***.***>:

**Comment by ludwich** [comment]
@reyntjensw Yes the daily & monthly and total power is not updating so we are not coming into that function for some reason.

**Comment by ludwich** [comment]
@reyntjensw the bug is on line 97 in device.js. if (Object.entries(basicStatsObj).length !== 0)  this is going to be 0 in length and function wont be called. if you go basicStatsObj.length that is 1 and the function will be called.

**Comment by Tschurl** [comment]
@reyntjensw same bug and another question: why are the values only every second minute available? 
![Screenshot_20230516-172236](https://github.com/reyntjensw/Homey-FusionSolar/assets/73354087/5438bb0f-def8-42ea-a16b-159745094bbf)
![Screenshot_20230516-172315](https://github.com/reyntjensw/Homey-FusionSolar/assets/73354087/28c26f49-c516-46e3-a5df-671e1724ee77)
![Screenshot_20230516-172417](https://github.com/reyntjensw/Homey-FusionSolar/assets/73354087/379d66fe-b998-4e21-b9c7-5fc4b4956a14)
![Screenshot_20230516-172518](https://github.com/reyntjensw/Homey-FusionSolar/assets/73354087/e10b7f6b-f8dd-4f18-8612-b281d0223bdd)

**Comment by BartDeWorm** [comment]
I have the same problem..
Can you help me to fix this? Or can I test something for you?
3e25f0ac-24e2-42a1-adb2-9325bd81d3f5

**Comment by reyntjensw** [comment]
@BartDeWorm can you please read this article and try the web method please? https://community.homey.app/t/app-pro-huawei-solar-smart-energy-for-a-better-life/61745/152?u=reyntjensw

**Comment by BartDeWorm** [comment]
Beste Wouter,

Heb het gevoel dat het probleem terug is..

Steeds een rood uitroepteken bij de omvormer en na herstart van de Homey
blijft die continu laden.

Kan je dit nogmaals nakijken aub?
Alvast bedankt!

Met vriendelijke groeten,
Bart De Worm


Op zo 28 mei 2023 21:40 schreef Wouter Reyntjens ***@***.***>:
