### ISSUE TITLE
Device Unavailable

### ISSUE THREAD

**Issue by nissenhj** [reyntjensw/Homey-FusionSolar#61]
Not getting it to work?  Neither with 1.0.57 nor 2.0.3

Getting Device Unavailable!
Invalid Capability: inverter_temperature, homey:app:com.huawei.solar

That's all I can come up with. 
API account works fine with BOVP.info on Windows computer
![Screenshot_20230521-135012](https://github.com/reyntjensw/Homey-FusionSolar/assets/45319576/24f518c5-7b94-4f16-86c7-032d569b55cf)

**Comment by reyntjensw** [comment]
@nissenhj the api apps will go EOL soon, please try the web version using the test version https://homey.app/a/com.huawei.solar/test/

**Comment by nissenhj** [comment]
> @nissenhj the api apps will go EOL soon, please try the web version using the test version https://homey.app/a/com.huawei.solar/test/

That will not work!
"The login credentials provided are not valid."
![Screenshot_20230521-210132](https://github.com/reyntjensw/Homey-FusionSolar/assets/45319576/184ef487-f4b8-4177-9af8-1aa4d69e7979)

**Comment by reyntjensw** [comment]
@nissenhj is the server you are using correct?
When you login on the webinterface, does the server correspond?

**Comment by dsellig** [comment]
I think he’s using the API credentials whereas he should be using the fusionsolar credentials.

**Comment by nissenhj** [comment]
> I think he’s using the API credentials whereas he should be using the fusionsolar credentials.

No, I don't
Today with the new test app it works!

**Comment by nissenhj** [comment]
> @nissenhj is the server you are using correct? When you login on the webinterface, does the server correspond?

With this new test app 2.0.6 you cannot see the temperature of the inverter.  Is it something you will put back?  My server is region02eu5.  API login works intermittently while Web login seems to work constantly

**Comment by reyntjensw** [comment]
@nissenhj If you want to have the temperature back, you can create a new issue for this.
I'll check if this information is available.
