### ISSUE TITLE
App nicht mehr nutzbar

### ISSUE THREAD

**Issue by willi-wolke** [reyntjensw/Homey-FusionSolar#63]
App läßt sich nicht mehr nutzen!
Version Befor 2023
Fehler:
    Invalid Capability: inverter_temperature, homey:app:com.huawei.solar

![Fehler](https://github.com/reyntjensw/Homey-FusionSolar/assets/134442689/bb291d17-7f3c-40d4-a024-4e19df7c3b38)

**Comment by reyntjensw** [comment]
Can you try this version please? https://homey.app/a/com.huawei.solar/test/

**Comment by willi-wolke** [comment]
Getestet mit Version 2.0.7
Neuer Fehler.
Ammeldung funktioniert.
Kapazität wird korrekt angezeigt
![Fehler2](https://github.com/reyntjensw/Homey-FusionSolar/assets/134442689/9e12b9dd-f477-4f09-b045-dba41be7a543)
![Fehler3](https://github.com/reyntjensw/Homey-FusionSolar/assets/134442689/0eef0c80-0245-442d-9f8f-756f67ad9944)
![Fehler4](https://github.com/reyntjensw/Homey-FusionSolar/assets/134442689/01aa209e-fc2a-4f96-89ec-fd41bfc73f3e)

**Comment by reyntjensw** [comment]
Could you please try the web version, this api version will not be supported anymore.
You need to use the web credentials instead of the api credentials.

**Comment by willi-wolke** [comment]
Läuft mit Huawei WEB!
