### ISSUE TITLE
Crashes every night

### ISSUE THREAD

**Issue by RoffPoff** [reyntjensw/Homey-FusionSolar#70]
Has to be restarted after crash.
Bug report
1431cfc4-9382-4e9b-850f-86192692b8c6

**Comment by powerklash** [comment]
With versione 2.0.9 It crash often than before, almost every 5 minutes. 
8c12c405-c0e1-4e5e-acc5-8c5942687e9c

**Comment by ludwich** [comment]
Same here crashes on every update of stats. @reyntjensw

**Comment by reyntjensw** [comment]
Guys I have no clue how to fix it, the logout feature is not working and I have no documentation.
I'm rolling back my change of last night

**Comment by reyntjensw** [comment]
New test version is out, please give it a try

**Comment by RoffPoff** [comment]
Progress! 2.0.11 survived the night without crash and is still running.
