### ISSUE TITLE
The readme.txt specifies to request en OpenAPI access account, while the description in the Homey app store says this will be deprecated this month. Which is correct?

### ISSUE THREAD

**Issue by Melmixx** [reyntjensw/Homey-FusionSolar#72]
Hi. Sorry I'm completely new, so it's really confusing for me and I cannot get this working. I'm very grateful for your hard work! Please could you be more specific about what people need to do and not contradict yourself depending on where we read? Some suggestions about the revised readme file:

1) Include if people should be using the web endpoint or the before 2023 or the after 2023. I got my inverter in late 2022 and I'm just not sure what to use. No matter what I use I can't get it to reliably read out the PV Yield. I've tried both version 2.0.8 and 2.0.11.

2) Include how to figure out which region you are assigned (1-5).

Thank you.

**Comment by jseverinson** [comment]
Hey. I'm not the developer, but I have answers for your questions nonetheless.

For region assignment, login to the web version at https://eu5.fusionsolar.huawei.com/ and once you're logged in look at the url. It will now be prepended with your assigned region.

For version, the developer of this app is moving away from the legacy REST API over to the web API that FusionSolar's own web client uses. With the legacy API you needed an API account. With the web client you use your regular credentials.

**Comment by reyntjensw** [comment]
@Melmixx the Readme has been modified
