### ISSUE TITLE
Homey Pro - Devices is null (in each option 'before OR after 2023 or Web'. 

### ISSUE THREAD

**Issue by Luc0001** [reyntjensw/Homey-FusionSolar#77]
Hello Wouter,

I've my Huawei account on region03eu5.fusionsolar.huawei.com.
Receive the SUN2000-3KTL-L1 converter and Luna2000 battery today.

Issue: no connection possible with Homey Pro, nor before 2023, after 2023 or Web.

Any clue what's missing or ...?

Thanks in advance for your time... Wkr... Luc

**Comment by Luc0001** [comment]
Hello Wouter,

Connection OK using your Web feature and the region03eu5 server.
I'll start experiencing.

Thanks for the Homey Pro interface.

Wkr... Luc

**Comment by reyntjensw** [comment]
Hi @Luc0001 thanks for your feedback!
