### ISSUE TITLE
Update of July 15th

### ISSUE THREAD

**Issue by rmangin** [reyntjensw/Homey-FusionSolar#80]
No integration working since last Huawei update (region02) : TypeError: response.data.data is not iterable.

**Comment by Melmixx** [comment]
Same for region03 this morning: Error retrieving data (TypeError: response.data.data is not iterable)

**Comment by rmangin** [comment]
Two days later the error changed into cannot read property status of undefined.
Simply delete the device and create as a new one and all worked perfectly fine.
Retrieved data seem more accurate than before :) Thanks
